= Changelog
:toc: auto

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [Unreleased]

=== Added
- Enhance integration tests for `commit` and `rollback` mojos;

=== Changes
- Refactored model classes to improve the maintainability
- Refactored add-dep` mojo to use new implementation;

=== Fixes
- Changed PomChangeTransaction class for maintainability improvement

== [0.0.3]

=== Added
- Added CHANGELOG documentation;
- Added CONTRIBUTING guide;
- Added issues templates;

=== Changes
- Updated README documentation;
- Moved project from ArrudaLabs to SouJava


== [0.0.3-SNAPSHOT] 2023-03-28T04:33:13Z

=== Added
- Added CHANGELOG documentation;
- Added CONTRIBUTING guide;
- Added issues templates;

=== Changes
- Updated README documentation;
- Moved project from ArrudaLabs to SouJava

== [0.0.2] 2023-03-23T23:46:43Z

=== Added
- Added the property called `gav` into the `add-dep` goal in order to inform the target dependency following the GAV(`groupId:artifactId:version`) pattern

=== Removed
- Removed the properties: `groupId`, `artifactId`, `version` in favor to use the `gav` property

== [0.0.1] - 2023-03-20T06:50:35Z

=== Added

- Added the `add-dep` maven goal in order to be able to add one dependency by time into a target POM
- Added the `commit` maven goal in order to be able to confirm the changes into the target POM, removing the backup POM file;
- Added the `rollback` maven goal in order to be able to revert the changes into the target POM;
