
= POM Editor Maven Plugin
:toc: auto

[%autowidth,cols="a,a", frame=none, grid=none, role="" ]
|===
| image:https://github.com/soujava/pom-editor-maven-plugin/actions/workflows/java-11.yml/badge.svg[ link=https://github.com/soujava/pom-editor-maven-plugin/actions/workflows/java-11.yml, window=_blank, target=_blank]
| image:https://img.shields.io/maven-central/v/br.org.soujava/pom-editor-maven-plugin?style=flat-square[Maven Central, link=https://central.sonatype.com/search?smo=true&namespace=br.org.soujava&q=br.org.soujava, window=_blank, target=_blank]
|===
== Introduction

Facilitate manipulation such as managing POM dependencies through CLI (command line interface)

== How to use it

Let's suppose that you need to add JUnit Jupiter version 5.9.2 into your POM in the test scope, you could perform the following command inside on the target maven project:

[source, sh]
----
mvn br.org.soujava:pom-editor:add-dep -Dgav='org.junit.jupiter:junit-jupiter:5.9.2' -Dscope=test
----

It's a Maven plugin then you may register the groupId into your `settings.xml` pluginGroups node :

[source,xml]
----
<settings >
    <!-- snipped -->
    <pluginGroups>
      <pluginGroup>br.org.soujava</pluginGroup>
    </pluginGroups>
    <!-- snipped -->
</settings>
----

Then you'll be able to perform the plugin by its prefix:

[source,sh]
----
mvn pom-editor:add-dep -Dgav='org.junit.jupiter:junit-jupiter:5.9.2' -Dscope=test
----

== Goals

It covers the following goals:

* Add/Change dependencies at POM.xml
* Rollback/Commit changes at POM.xml


== Contributing

We are very happy you are interested in helping us and there are plenty ways you can do so.

- https://github.com/arrudalabs/pom-editor-maven-plugin/issues[**Open an Issue:**]  Recommend improvements, changes and report bugs

- **Open a Pull Request:** If you feel like you can even make changes to our source code and suggest them, just check out our link:CONTRIBUTING.adoc[contributing guide] to learn about the development process, how to suggest bugfixes and improvements.

== Contact

Join the link:https://discord.gg/eAARnH7yrG[SouJava Discord server] and say hello at `#pom-editor-maven-plugin` channel!