name: Documentation Update 📝

description: Improve Documentation
title: "[Documentation Update]: "
labels: 'documentation'
body:
  - type: input
    id: existing-issue-link
    attributes:
      label: Link to Existing Issue
      description: If an issue already exists for this update, please provide the link. Otherwise, leave it blank.
      placeholder: "https://github.com/owner/repository/issues/123"
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please provide a clear description of the documentation update you are suggesting.
      placeholder: Describe the improvement or correction you'd like to see in the documentation.
    validations:
      required: true
  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: Provide details of the proposed change to the documentation.
      placeholder: Explain how the documentation should be updated or corrected.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this documentation update necessary or beneficial?
      placeholder: Explain the importance or reasoning behind the suggested change.
    validations:
      required: false
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgently do you believe this documentation update is needed?
      options:
        - High
        - Medium
        - Low
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I have read the Contributing Guidelines"
          required: true
        - label: "I have starred the repository"
          required: false  # Made optional so users are not forced to star the repo
