name: Feature Request ✨
description: Suggest a feature
title: "[Feature Request] "
labels: enhancement
body:
  - type: input
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: "If there is an existing issue related to this feature request, please provide the link. Otherwise, you may leave this blank."
      placeholder: "https://github.com/owner/repository/issues/123"
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a detailed description of the feature you are requesting.
      placeholder: Describe the new feature or enhancement you'd like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature enhance your use of the project?
      placeholder: Describe a specific use case or scenario where this feature would be beneficial.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature bring to the project or community?
      placeholder: Explain the advantages of implementing this feature.
  - type: textarea
    id: screenshots
    attributes:
      label: Add Screenshots
      description: If applicable, add screenshots or visual references.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High
        - Medium
        - Low
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I have read the Contributing Guidelines"
          required: true
        - label: "I have starred the repository"
          required: false  # Made optional so users are not forced to star the repo
