name: New Goal Proposal 
title: '[New Goal Proposal]: '
description: Open a goal request
labels: ["enhancement","proposal","question","help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the required information requested. Goal requests that do not follow this format are likely to stall.

  - type: textarea
    id: purpose-goal
    attributes:
      label: What is the purpose of the new goal?
      description: |
        Please provide a clear and concise purpose for the goal that you're requesting. 
        Feel free to Include screenshots if needed.
    validations:
      required: true

  - type: textarea
    id: expected-behavior-and-output
    attributes:
      label: What is the expected behavior and output of the new goal?
      description: |
        Please provide the following information (Feel free to Include screenshots if needed):
        - the goal syntax;
        - the required inputs;
        - the expected behavior;
        - the expected output;
      value: |
        ### Given the pom:
        ```xml
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>anyGroupId</groupId>
            <artifactId>anyArtifactId</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <packaging>pom</packaging>
        </project>
        ```
        ### When execute:
        ```sh
        mvn pom-editor:<new goal> [-DnewParams=?]
        ```
        ### Expected output or result:
        <!-- describe here the expected output or result -->
    validations:
      required: true

